### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by sbilly** [t13a/helm-chart-freshrss#1]
How to install freshrss with helm ?

**Comment by t13a** [comment]
Sorry for the lack of documentation.

1. Provision PV & PVC & MariaDB in advance
2. install the chart with `--set persistence.existingClaim=PVC_NAME` (or `--values=your-values.yaml`)

My `values.yaml` is like below:

```yaml
cronjob:
  enabled: true
  schedule: "15 * * * *" # 15 minutes per hour
  activeDeadlineSeconds: 1800 # 30m
ingress:
  enabled: true
  hosts:
  - freshrss.mydomain.tld
  tls:
  - secretName: freshrss-tls
    hosts:
    - freshrss.mydomain.tld
persistence:
  existingClaim: freshrss-data
extraVolumeMounts:
- name: extensions
  mountPath: /var/www/FreshRSS/extensions
extraVolumes:
- name: extensions
  persistentVolumeClaim:
    claimName: freshrss-extensions
```
